
server:
  port: 8081
  ssl:
    key-store: C:\Users\hp\Desktop\SNI-Project\dms\keystore.p12
    key-store-password: sigurnost
    keyStoreType: PKCS12
    keyAlias: tomcat
#keycloak:
#  realm: SNI
#  auth-server-url: http://localhost:8180/auth
#  resource: dms
#  public-client: true
#  bearer-only: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dms?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: student
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update